fix: leverage builderWithDefaults to decouple handling of default values
dekorateio/dekorate pull request #1008
Opened 2022-06-29 14:31 UTC by iocanel

2022-06-29 14:35 UTC, iocanel commented
This will also deal with issues reported on Quarkus by @spolti

2022-06-29 14:38 UTC, spolti approved these changes

2022-06-30 04:33 UTC, Sgitario requested changes
If I understood well the issue, the problem is that the default value from annotations is ignored when mapping the annotations to the actual properties? If this is right, I would look into a more general solution that also fixes this for Kubernetes, OpenShift, and other generators.

Also, I think either an integration test or simply a unit test should be added to reproduce the issue and confirm it's solved.

2022-06-30 06:54 UTC, iocanel commented
> If I understood well the issue, the problem is that the default value from annotations is ignored when mapping the annotations to the actual properties?

Not exactly, Default values are respected fine. The issue is that we apply dekorators even when the default value is present in the config objects. Again, this is desired in dekorate land, but if dekorate is used downstream without dekorate's own config model, this is causing issues.

> Also, I think either an integration test or simply a unit test should be added to reproduce the issue and confirm it's solved.

An itnegration test is not possible, as in the dekorate land there is no problem. I'll check to see if we can have a unit test that checks if the registered dekorators are the expected ones.

2022-06-30 19:56 UTC, iocanel commented
@Sgitario: Added ingtegration test that verify that the dekorators are only registrered when non default options are provided. How? By providing existing resources with non-default configuration and checking that they are respected.

2022-07-01 04:50 UTC, Sgitario commented on core/src/main/java/io/dekorate/AbstractKubernetesManifestGenerator.java
>        resourceRegistry.decorate(group, new ApplyImagePullPolicyDecorator(config.getImagePullPolicy()));
missing the first parameter `config.getName()` here

2022-07-01 05:17 UTC, Sgitario reviewed
Thanks for adding the test. I see what the issue is resolving now. 
There are some failures, apart from it, the changes look good to me.

2022-07-01 11:34 UTC, Sgitario approved these changes

2022-07-04 12:16 UTC, merged