WIP feat: add frameworkless on openshift to the examples
dekorateio/dekorate pull request #605
Opened 2020-07-30 13:49 UTC by aureamunoz

2020-12-10 14:53 UTC, aureamunoz commented
This can be reviewed @iocanel . Do you want me to add also the examples using `JIB`?

2021-02-10 16:36 UTC, aureamunoz commented
Can you mark this PR as `Draft` @iocanel ? It seems I'm not able to do it

2021-02-18 14:46 UTC, cmoulliard commented
This PR has been created long time ago Jul 2020. What is the status of this work ? 
Will it become part of the release 2.0 ?
@aureamunoz @iocanel

2021-02-18 14:59 UTC, iocanel commented
> This PR has been created long time ago Jul 2020. What is the status of this work ?
> Will it become part of the release 2.0 ?
> @aureamunoz @iocanel

It's not mandatory for 2.0, but I'd like to get this in. We are working on it.

2021-02-20 10:06 UTC, iocanel requested changes
I really really love the concept and the code looks great!

I've requrested some changes all styling related:
- remove commented out code.
- algin naming: Use `kubernetes` instead of `k8s`
- Use a smaller name in the examples: `frameworkles-` instead of `rest-api-frameworkless-`
- Use the common `io.dekorate.example` as the package for the examples
- Do not use collapsed packages in a signle directory.
- Remove configuration options that are environment specific (e.g. realted to minikube) or not absolutely needed (e.g. custom names).
- Use placeholders for dependency and plugin version in poms.

2021-02-20 10:06 UTC, iocanel commented on examples/rest-api-frameworkless-on-openshift-with-docker-example/readme.md
> +        imagePullPolicy = ImagePullPolicy.Always
name and pull policy should probably go.

2021-02-20 10:06 UTC, iocanel commented on examples/rest-api-frameworkless-on-openshift-with-docker-example/src/main/java/io.dekorate.fwlonopenshift/App.java
> +@OpenshiftApplication(name = "hello-world-fwless-openshift",
name and image pull policy should better go, as explained above.

2021-02-22 11:38 UTC, iocanel requested changes
Added a couple of more remarks:
- align readme with actual code.
- fix a mainClass reference in the k8s example.

Other than that I think we are great!

2021-02-22 11:38 UTC, iocanel commented on examples/frameworkless-on-openshift-with-docker-example/pom.xml
> +              <mainClass>io.dekorate.fwlonopenshift.App</mainClass>
We need to update this now that the package is changed.

2021-02-22 11:38 UTC, iocanel commented on examples/frameworkless-on-kubernetes-example/readme.md
> +@KubernetesApplication(
We need to align this with the current content of the class  (e.g. remove name, imagePullPolicy)

2021-02-22 11:38 UTC, iocanel commented on examples/frameworkless-on-openshift-with-docker-example/readme.md
> +        ports = @Port(name = "web", containerPort = 8080),
Same as with the kubernetes example. We need to align this (remove uneeded options)

2021-02-22 14:43 UTC, aureamunoz commented
Finally the Openshift example uses the s2i build. Commits squashed, master rebased. It should be green. Would you like to take a look? Once the CI finish we can merge @iocanel.

2021-02-22 14:49 UTC, iocanel reviewed
LGTM, once CI is green we can merge.

2021-02-22 15:21 UTC, merged