Configuration for primitives is not taken into account, default value has higher priority
dekorateio/dekorate pull request #736
Opened 2021-03-02 15:01 UTC by aureamunoz

Related to #706 
This is not completely fixed but contains some needed code. This PR fixes the hard code for replicas, improve the test and remove default value for replicas in k8s application config

2021-03-26 17:04 UTC, aureamunoz commented
I have pushed some modifications that I had locally and I think that can worth it. Could you take a look if you are some spare time @iocanel ? Thank you very much!! this is no a draft anymore

2021-04-06 10:00 UTC, iocanel commented
@aureamunoz: I expect this to be fixed in 2.x. Do you still have issues around it?

2021-04-06 10:11 UTC, aureamunoz commented
2.x is the master, isn't it?
No, I don't have any issue, it's just some code that I hadn't pushed when working on it. Basically, the test has been improved and the hardcoding of replicas removed.

2021-04-08 06:27 UTC, iocanel commented
@aureamunoz: great! Then I'll proceed with the review so that we can get it merged asap.

2021-04-08 06:30 UTC, iocanel requested changes
Overall looks good. The only thing I'd like to change is to remove the serviceType stuff from DemoApplication in order to keep it as minimal as possible. Unless of course they serve a purpose for the test, in which case a comment explaining the purpose would be needed.

2021-04-08 06:30 UTC, iocanel commented on annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java
> +        .withReplicas(appConfig.getReplicas())
BTW, this is more of a remark, rather than a change request.

2021-04-08 06:30 UTC, iocanel commented on tests/issue-331-annotation-combined-with-properties/src/main/java/io/dekorate/annotationless/DemoApplication.java
> +@KubernetesApplication(replicas = 3, serviceType = ServiceType.NodePort, serviceAccount = "test", ports = {
I'd rather we removed that.

2021-04-08 09:59 UTC, aureamunoz commented on annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java
> -  int replicas() default 1;
yes, I had fixed it in the second commit: https://github.com/dekorateio/dekorate/pull/736/commits/a9e75e954d7ec9865913924fa4ca213edbe565ff

2021-04-08 10:04 UTC, aureamunoz commented on annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/manifest/KubernetesManifestGenerator.java
> +        .withReplicas(appConfig.getReplicas())
ok, not very intuitive :-)

2021-04-08 10:06 UTC, aureamunoz commented on tests/issue-331-annotation-combined-with-properties/src/main/java/io/dekorate/annotationless/DemoApplication.java
> +@KubernetesApplication(replicas = 3, serviceType = ServiceType.NodePort, serviceAccount = "test", ports = {
ok, I will remove it. I don't remember, I think I was testing different cases.

2021-04-08 10:16 UTC, aureamunoz commented
I took into account your comments @iocanel and rebase onto master, let's see what CI says :-)

2021-04-09 06:03 UTC, iocanel approved these changes
LGTM

2021-04-09 07:55 UTC, merged