Invalid logger breaks current application flow
dekorateio/dekorate pull request #753
Opened 2021-04-27 12:32 UTC by pjgg

Instead of throw an `IllegalStateException` exception we could log an `error` msg and swap to a standard std out.

Related issue: https://github.com/quarkusio/quarkus/issues/15953

2021-05-06 18:37 UTC, iocanel requested changes
Thanks for the pull request.
I have a minor aesthetic change request. Other than that it looks good.

2021-05-06 18:37 UTC, iocanel commented on core/src/main/java/io/dekorate/logger/AnsiLogger.java
> +      stream = new PrintStream(new FileOutputStream(FileDescriptor.out));
I wouldn't use Asciiart for something that is actually an error message.

2021-05-10 07:05 UTC, iocanel approved these changes
LGTM

2021-05-10 07:06 UTC, merged

2021-05-10 16:22 UTC, geoand commented
@iocanel can we get a release of this that we then incorporate in Quarkus?

2021-05-10 18:13 UTC, iocanel commented
Will try to release later tonight or tomorrow morning!

On Mon, May 10, 2021, 7:23 PM Georgios Andrianakis ***@***.***>
wrote:

> @iocanel <https://github.com/iocanel> can we get a release of this that
> we then incorporate in Quarkus?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dekorateio/dekorate/pull/753#issuecomment-836916186>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADCEWGYAYD32SPGF5AO4QLTNAB7NANCNFSM43U42VTA>
> .
>

2021-05-10 19:01 UTC, geoand commented
Thanks!

2021-05-11 08:07 UTC, iocanel commented
@pjgg: I have some `just a little` late questions:

- Does this pull request solve the issue with quarkus (Have you verified the fix)?
- Do you think that we should also bump jansi to a later version ?
- Why do you use `new FileOutputStream(FileDescriptor.out)` vs `System.out`?