Support Job for Openshift, Knative and Kubernetes
dekorateio/dekorate pull request #881
Opened 2022-02-28 11:00 UTC by Sgitario

More information in the feature request: https://github.com/dekorateio/dekorate/issues/856
Fix https://github.com/dekorateio/dekorate/issues/856

2022-03-01 20:44 UTC, aureamunoz requested changes

2022-03-01 20:44 UTC, aureamunoz commented on docs/documentation/kubernetes.md
> +Currently, the supported annotations for adding Kubernetes Jobs are:
```suggestion
Currently, the supported annotations for adding jobs are:
```

2022-03-01 20:44 UTC, aureamunoz commented on docs/documentation/kubernetes.md
> +- @KnativeApplication
It should be nice to add this paragraph also to the Knative and OpenShift `docs/documentation/md` files, wdyt?

2022-03-02 08:16 UTC, iocanel requested changes
I am not sure if we should get into the business of defining arbitrary jobs via dekorate.
When I first heard about Job support in Kubernetes, I thought that the goal is to expose the application in development as a Job, rather than being able to define side jobs.

Let's meet and discuss.

2022-03-03 11:49 UTC, Sgitario commented
> I am not sure if we should get into the business of defining arbitrary jobs via dekorate. When I first heard about Job support in Kubernetes, I thought that the goal is to expose the application in development as a Job, rather than being able to define side jobs.
> 
> Let's meet and discuss.

As discussed, for Jobs, we're going to discuss two use cases:
- The generation of side Jobs. This is implemented as part of this PR. 
- Allow setting the kind output which will be implemented in https://github.com/dekorateio/dekorate/issues/886.

2022-03-03 11:50 UTC, Sgitario commented
@iocanel I've already updated this PR with the support of volumes.

2022-03-10 13:44 UTC, iocanel approved these changes
LGTM

2022-03-14 06:02 UTC, merged