feat: support generation of cronjobs
dekorateio/dekorate pull request #892
Opened 2022-03-23 11:31 UTC by Sgitario

More information in the feature request: https://github.com/dekorateio/dekorate/issues/855
Fix https://github.com/dekorateio/dekorate/issues/855

2022-03-24 11:08 UTC, aureamunoz reviewed
LGTM but docs are missing, right?

2022-03-24 11:37 UTC, Sgitario commented
> LGTM but docs are missing, right?

Ups. Added.

2022-03-24 11:38 UTC, aureamunoz approved these changes
Perfect. thanks

2022-03-24 11:42 UTC, aureamunoz requested changes
mmm, I sent the ok too fast. Could you add a link to the [spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec) also? And maybe quote the fact that Dekorate should use the pod template image configuration if user doesn't provide a cron specific one?

2022-03-24 11:45 UTC, Sgitario commented
> mmm, I sent the ok too fast. Could you add a link to the [spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec) also? And maybe quote the fact that Dekorate should use the pod template image configuration if user doesn't provide a cron specific one?

- Where do you think I should the link in? 
- I don't understand your last sentence

2022-03-24 12:02 UTC, aureamunoz requested changes

2022-03-24 12:02 UTC, aureamunoz commented on docs/documentation/kubernetes.md
> +
```suggestion
Dekorate CronJobs configuration follows the [Kubernetes CronJobs specification](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec). 

If the user doesn't provide CronJob container image, the pod template image configuration will be used.
```

2022-03-24 12:02 UTC, aureamunoz commented on docs/documentation/openshift.md
> +
```suggestion
Dekorate CronJobs configuration follows the [Kubernetes CronJobs specification](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/#CronJobSpec). 

If the user doesn't provide CronJob container image, the pod template image configuration will be used.
```

2022-03-24 12:49 UTC, aureamunoz approved these changes

2022-04-04 13:14 UTC, iocanel approved these changes
LGTM

2022-04-04 13:14 UTC, merged